### ISSUE TITLE
Visualization Predictive Power

### ISSUE THREAD

**Issue by jinchen1036** [jinchen1036/DataScience_Project#16]
Acceptance Criteria:
- Have at least two visualization that demonstrates the predictive power of data and model.
- Options
   - [ROC curve](https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html) - for model
   - Plot actual rent and prediction rent (in different colors) - for data

**Comment by shinzhao** [comment]
ROC curve only exists for classification problems, so we're gonna skip that one.

**Comment by jinchen1036** [comment]
Add https://github.com/jinchen1036/DataScience_Project/blob/master/visualization.py for data visualization
